-- Crear la tabla de productos (cervezas)
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  type text, -- Ej: Blonde Ale, Stout, IPA
  description text,
  abv numeric, -- Alcohol by Volume
  ibu numeric, -- Bitterness
  price numeric, -- Precio sugerido
  stock integer default 0,
  pairing text, -- Maridaje recomendado
  metadata jsonb -- Para guardar info extra como color, frase, etc.
);

-- Habilitar la extensión para búsquedas de texto (opcional pero recomendado)
create extension if not exists pg_trgm;

-- Insertar los datos basados en el archivo Personajes.md
insert into products (name, type, description, abv, ibu, price, stock, pairing, metadata) values
(
  'La Catira', 
  'Blonde Ale / Golden Ale', 
  'Rubia refrescante, tropical, ligera y chispeante con notas cítricas. Representa el verano eterno.', 
  4.5, 
  18, 
  3.50, 
  120, 
  'Pescado frito, ceviche, ensaladas frescas.',
  '{"catchphrase": "No hay olas malas, solo malas vibras", "character": "La Catira"}'
),
(
  'La Morena', 
  'Brown Ale / Porter', 
  'Cerveza tostada con notas de caramelo y miel. Dulce, intensa, con cuerpo y alma.', 
  6.0, 
  25, 
  4.20, 
  85, 
  'Carnes a la parrilla, estofados, postres de chocolate.',
  '{"catchphrase": "No bailes conmigo si no puedes seguir el ritmo", "character": "La Morena"}'
),
(
  'La Sifrina', 
  'Blonde Ale (Gluten Free)', 
  'Suave, refinada y moderna, con un toque floral y afrutado. La opción chic y ligera.', 
  4.2, 
  15, 
  4.50, 
  60, 
  'Sushi, brunchs, quesos suaves.',
  '{"catchphrase": "El estilo no se compra, se destila", "character": "La Sifrina"}'
),
(
  'Candela', 
  'Imperial Stout', 
  'Oscura, intensa, con notas de cacao, café y fuego interior. Potente y con carácter.', 
  8.5, 
  60, 
  5.50, 
  40, 
  'Quesos azules, brownies, carnes ahumadas.',
  '{"catchphrase": "Si no puedes con el calor, no entres en mi pista", "character": "Candela"}'
),
(
  'Guajira', 
  'Tropical IPA', 
  'IPA tropical con maracuyá. Frutal, exótica y equilibrada entre dulzura y frescura.', 
  5.8, 
  45, 
  4.80, 
  90, 
  'Comida picante, tacos, curry.',
  '{"catchphrase": "Don’t rush the vibe, just feel it", "character": "La Guajira"}'
),
(
  'Medusa 0,0', 
  'Sin Alcohol (0.0)', 
  'Ligeramente frutal, chispeante y vibrante. Todo el sabor sin alcohol.', 
  0.0, 
  12, 
  3.00, 
  150, 
  'Almuerzos de trabajo, hidratación post-yoga.',
  '{"catchphrase": "Cero culpa, cien por cien actitud", "character": "Medusa 0,0"}'
);
