-- Crear la tabla de productos (cervezas)
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  type text, -- Ej: Blonde Ale, Stout, IPA
  description text,
  abv numeric, -- Alcohol by Volume
  ibu numeric, -- Bitterness
  price numeric, -- Precio sugerido
  stock integer default 0,
  pairing text, -- Maridaje recomendado
  metadata jsonb -- Para guardar info extra como color, frase, etc.
);

-- Habilitar la extensión para búsquedas de texto (opcional pero recomendado)
create extension if not exists pg_trgm;

-- Insertar los datos basados en el archivo Personajes.md
insert into products (name, type, description, abv, ibu, price, stock, pairing, metadata) values
(
  'La Catira', 
  'Blonde Ale / Golden Ale', 
  'Rubia refrescante, tropical, ligera y chispeante con notas cítricas. Representa el verano eterno.', 
  4.5, 
  18, 
  3.50, 
  120, 
  'Pescado frito, ceviche, ensaladas frescas.',
  '{"catchphrase": "No hay olas malas, solo malas vibras", "character": "La Catira"}'
),
(
  'La Morena', 
  'Brown Ale / Porter', 
  'Cerveza tostada con notas de caramelo y miel. Dulce, intensa, con cuerpo y alma.', 
  6.0, 
  25, 
  4.20, 
  85, 
  'Carnes a la parrilla, estofados, postres de chocolate.',
  '{"catchphrase": "No bailes conmigo si no puedes seguir el ritmo", "character": "La Morena"}'
),
(
  'La Sifrina', 
  'Blonde Ale (Gluten Free)', 
  'Suave, refinada y moderna, con un toque floral y afrutado. La opción chic y ligera.', 
  4.2, 
  15, 
  4.50, 
  60, 
  'Sushi, brunchs, quesos suaves.',
  '{"catchphrase": "El estilo no se compra, se destila", "character": "La Sifrina"}'
),
(
  'Candela', 
  'Imperial Stout', 
  'Oscura, intensa, con notas de cacao, café y fuego interior. Potente y con carácter.', 
  8.5, 
  60, 
  5.50, 
  40, 
  'Quesos azules, brownies, carnes ahumadas.',
  '{"catchphrase": "Si no puedes con el calor, no entres en mi pista", "character": "Candela"}'
),
(
  'Guajira', 
  'Tropical IPA', 
  'IPA tropical con maracuyá. Frutal, exótica y equilibrada entre dulzura y frescura.', 
  5.8, 
  45, 
  4.80, 
  90, 
  'Comida picante, tacos, curry.',
  '{"catchphrase": "Don’t rush the vibe, just feel it", "character": "La Guajira"}'
),
(
  'Medusa 0,0',
  'Sin Alcohol (0.0)',
  'Ligeramente frutal, chispeante y vibrante. Todo el sabor sin alcohol.',
  0.0,
  12,
  3.00,
  150,
  'Almuerzos de trabajo, hidratación post-yoga.',
  '{"catchphrase": "Cero culpa, cien por cien actitud", "character": "Medusa 0,0"}'
);

-- Crear la tabla de tiendas/locales
create table if not exists stores (
  id bigint generated by default as identity primary key,
  name text not null,
  category text, -- Pub, Bar, Restaurante, Supermercado, etc.
  city text,
  zone text, -- Barrio o zona (ej: 'San Blas', 'Centro', 'Playa San Juan')
  address text,
  latitude decimal(10, 8), -- Coordenadas para búsqueda geoespacial
  longitude decimal(11, 8),
  google_maps_url text, -- URL de Google Maps (alternativa a lat/lng)
  phone text,
  website text,
  opening_hours jsonb, -- Horarios de apertura
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Índice para búsqueda por texto en stores
create index if not exists idx_stores_city on stores using gin (city gin_trgm_ops);
create index if not exists idx_stores_zone on stores using gin (zone gin_trgm_ops);
create index if not exists idx_stores_name on stores using gin (name gin_trgm_ops);

-- Crear la tabla de eventos
create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  location text,
  store_id bigint references stores(id), -- Opcionalmente vinculado a una tienda
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Ejemplo de tiendas (descomentar y ajustar según tus locales reales)
/*
insert into stores (name, category, city, zone, address, google_maps_url) values
(
  'Nzca Peru',
  'Restaurante',
  'Alicante',
  'Centro',
  'Calle ejemplo 123, Alicante',
  'https://www.google.com/maps/place/Nzca+Peru/@38.3420936,-0.495882,17z/data=!3m1!4b1!4m6!3m5!1s0xd62377e56bee6db:0x46e6ba6ecb3446a9!8m2!3d38.3420936!4d-0.4933071!16s%2Fg%2F11wwqrx43r'
);
*/
